from tkinter import *
# criação de botoēs
class ButtaoPersonalizado:
    def __init__(self, button, text):
            button["text"] = text
            button["font"] = ("Times", "14")
            button['background'] = 'purple'
            button["width"] = 10
            button.pack()
# personaluzação da parte superior do cod
class Application:
    def __init__(self, master=None):
            self.widget1 = Frame(master)
            self.widget1.pack()
            self.msg = Label(self.widget1, text="",bg="#660066")
            self.msg.pack()
            self.widget2 = Frame(master,bg='#660066')
            self.widget2.pack()
            self.msg = Label(self.widget2, text="             Casa do Açai           ",bg="#660066")
            self.msg.pack()
# personalização do botão
            self.bt1 = Button(self.widget2)
            ButtaoPersonalizado(self.bt1, " Cardápio" )
            self.widget9 = Frame(master)
            self.widget9.pack()
# textos que serão emitidos na tela 
            self.msg = Label(self.widget9,
                             text="                           ",bg="#660066")
            self.msg.pack()
            self.widget9 = Frame(master)
            self.widget9.pack()
            self.msg = Label(self.widget9, text="  ",bg="#660066")
            self.msg.pack()
            self.widget9 = Frame(master)
            self.widget9.pack()
            self.msg = Label(self.widget9, text="  ",bg="#660066")
            self.msg.pack()
            self.widget9 = Frame(master)
            self.widget9.pack()
            self.msg = Label(self.widget9, text="  ",bg="#660066")
            self.msg.pack()
            self.widget9 = Frame(master)
            self.widget9.pack()
            self.msg = Label(self.widget9, text="  ",bg="#660066")
            self.msg.pack()
            self.widget9 = Frame(master)
            self.widget9.pack()
            self.msg = Label(self.widget9, text="  ",bg="#660066")
            self.msg.pack()
            self.widget9 = Frame(master)
            self.widget9.pack()
            self.msg = Label(self.widget9, text="  ",bg="#660066")
            self.msg.pack()
            self.widget9 = Frame(master)
            self.widget9.pack()
            self.msg = Label(self.widget9, text="  ",bg="#660066")
            self.msg.pack()
            self.widget9 = Frame(master)
            self.widget9.pack()
            self.msg = Label(self.widget9, text="  ",bg="#660066")
            self.msg.pack()
            self.widget9 = Frame(master)
            self.widget9.pack()
            self.msg = Label(self.widget9, text=" Seja Bem Vindo a nossas pagina,  Clique em Cardapio e veja nossos Produtos,  ",bg="#660066")
            self.msg["font"] = ("Times", "14", "italic")
            self.msg.pack()
            self.widget9 = Frame(master)
            self.widget9.pack()
            self.msg = Label(self.widget9, text=" Lembrando que você ganha 70% de desconto ",bg="#660066")
            self.msg["font"] = ("Times", "14", "italic")
            self.msg.pack()
            self.widget9 = Frame(master)
            self.widget9.pack()
            self.msg = Label(self.widget9, text=" na sua primeira comprar, Aproveite!!",bg="#660066")
            self.msg["font"] = ("Times", "14", "italic")
            self.msg.pack()
            self.widget9 = Frame(master)
            self.widget9.pack()
            self.msg = Label(self.widget9, text=" venha aqui tem o melhor Açai de Porto Velho  ",bg="#660066")
            self.msg["font"] = ("Times", "14", "italic")
            self.msg.pack()
            self.widget9 = Frame(master)
            self.widget9.pack()
            self.msg = Label(self.widget9, text="  ",bg="#660066")
            self.msg.pack()
            self.widget9 = Frame(master)
            self.widget9.pack()
            self.msg = Label(self.widget9, text=" Autor Gráfico: Matheus Henrique M.Nunes", bg="#660066")
            self.msg["font"] = ("Times", "14", "italic")
            self.msg.pack()
            self.widget9 = Frame(master)
            self.widget9.pack()
            


root = Tk()
root ["bg"] ="#660066"
root.title("www.casadoAçai.com.br")
Application()
root.mainloop()